# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 556e8860b171a60b5907deca9cee14d1f90e31d234e414f4099af570f9dc1c9cb0c0817fd862f9d4fbf2b32c651010c1f8bef69b542cf30f663a5993557a5f5d

test:
  secret_key_base: 2ded30df4c0875507d8c0e2cca4cc3bfcea60a59fb279c482aadad3b53695041d18adb87ac5f21af995cd6fee7aed8e31cc692f945545fe7755d3e3e590a78b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
