# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Store.create(name: 'м. Автозаводская', country: 'Россия', city: 'Москва', address: 'ул. Ленинская Слобода, 26', phone_number: '+7 (495) 803-42-36', postal_code: 115280, working_hours: 'Ежедневно: 10:00—22:00')
Store.create(name: 'м. Библиотека им. Ленина', country: 'Россия', city: 'Москва', address: 'ул. Воздвиженка, 4/7, стр. 1', phone_number: '+7 (499) 270-00-52', postal_code: 125009, working_hours: 'Круглосуточно')
Store.create(name: 'м. Войковская', country: 'Россия', city: 'Москва', address: 'Ленинградское ш., 16А, корп. 2', phone_number: '+7 (495) 287-00-47', postal_code: 125171, working_hours: 'Ежедневно: 10:00—22:00')
Store.create(name: 'м. Дмитровская', country: 'Россия', city: 'Москва', address: 'ул. Большая Новодмитровская, 36', phone_number: '+7 (495) 642-71-80', postal_code: 127015, working_hours: 'Ежедневно: 10:00—22:00')

Category.create(name: 'Книги')
Category.create(name: 'Канцелярия')
Category.create(name: 'Дом')
Category.create(name: 'Аксессуары')
Category.create(name: 'Электроника')
Category.create(name: 'Хобби и творчество')

Product.create(category_id: 1, name: 'Мишки на каникулах')
Product.create(category_id: 1, name: '14 лесных мышей. Пикник')
Product.create(category_id: 1, name: 'Дети взрослым не игрушки')
Product.create(category_id: 2, name: 'Тетрадь "In black" А5 в клетку')
Product.create(category_id: 2, name: 'Набор капиллярных ручек "Link-It"')
Product.create(category_id: 2, name: 'Еженедельник Academic 2018 А5 датированный')
Product.create(category_id: 3, name: 'Фигурка "Lucky cat", розовая')
Product.create(category_id: 3, name: 'Ароматический диффузор "Удачи"')
Product.create(category_id: 3, name: 'Открывашка для бутылок "Flash"')
Product.create(category_id: 4, name: 'Значок эмалированный')
Product.create(category_id: 4, name: 'Обложка для проездного билета')
Product.create(category_id: 4, name: 'Носки "Забивака с мячом')
Product.create(category_id: 5, name: 'USB-Hub на 4 порта USB2.0')
Product.create(category_id: 5, name: 'Кабель NyloGlitz Lightning MFI Black')
Product.create(category_id: 5, name: 'Набор Instax Mini 9 Pink Set Champion')
Product.create(category_id: 6, name: 'Карандаши акварельные Milan')
Product.create(category_id: 6, name: 'Фломастеры Milan 12 цветов')
Product.create(category_id: 6, name: 'Паста для моделирования JOVI')

StoresProduct.create(store_id: 1, product_id: 1, price: 594.23)
StoresProduct.create(store_id: 1, product_id: 2, price: 739.61)
StoresProduct.create(store_id: 1, product_id: 3, price: 522.34)
StoresProduct.create(store_id: 1, product_id: 4, price: 976.60)
StoresProduct.create(store_id: 1, product_id: 5, price: 904.90)
StoresProduct.create(store_id: 1, product_id: 6, price: 850.36)
StoresProduct.create(store_id: 1, product_id: 7, price: 817.96)
StoresProduct.create(store_id: 1, product_id: 8, price: 422.18)
StoresProduct.create(store_id: 1, product_id: 9, price: 51.34)
StoresProduct.create(store_id: 1, product_id: 10, price: 901.30)
StoresProduct.create(store_id: 1, product_id: 11, price: 270.27)
StoresProduct.create(store_id: 1, product_id: 12, price: 354.48)
StoresProduct.create(store_id: 1, product_id: 13, price: 441.62)
StoresProduct.create(store_id: 1, product_id: 14, price: 844.82)
StoresProduct.create(store_id: 1, product_id: 15, price: 990.93)
StoresProduct.create(store_id: 1, product_id: 16, price: 365.27)
StoresProduct.create(store_id: 1, product_id: 17, price: 864.52)
StoresProduct.create(store_id: 1, product_id: 18, price: 467.98)

StoresProduct.create(store_id: 2, product_id: 1, price: 490.44)
StoresProduct.create(store_id: 2, product_id: 2, price: 617.01)
StoresProduct.create(store_id: 2, product_id: 3, price: 664.60)
StoresProduct.create(store_id: 2, product_id: 4, price: 392.28)
StoresProduct.create(store_id: 2, product_id: 5, price: 358.42)
StoresProduct.create(store_id: 2, product_id: 6, price: 437.08)
StoresProduct.create(store_id: 2, product_id: 7, price: 153.62)
StoresProduct.create(store_id: 2, product_id: 8, price: 155.55)
StoresProduct.create(store_id: 2, product_id: 9, price: 426.73)
StoresProduct.create(store_id: 2, product_id: 10, price: 693.43)
StoresProduct.create(store_id: 2, product_id: 11, price: 572.90)
StoresProduct.create(store_id: 2, product_id: 12, price: 189.53)
StoresProduct.create(store_id: 2, product_id: 13, price: 713.27)
StoresProduct.create(store_id: 2, product_id: 14, price: 214.02)
StoresProduct.create(store_id: 2, product_id: 15, price: 540.58)
StoresProduct.create(store_id: 2, product_id: 16, price: 159.88)
StoresProduct.create(store_id: 2, product_id: 17, price: 993.56)
StoresProduct.create(store_id: 2, product_id: 18, price: 870.61)

StoresProduct.create(store_id: 3, product_id: 1, price: 274.20)
StoresProduct.create(store_id: 3, product_id: 2, price: 296.14)
StoresProduct.create(store_id: 3, product_id: 3, price: 500.80)
StoresProduct.create(store_id: 3, product_id: 4, price: 131.32)
StoresProduct.create(store_id: 3, product_id: 5, price: 910.15)
StoresProduct.create(store_id: 3, product_id: 6, price: 835.49)
StoresProduct.create(store_id: 3, product_id: 7, price: 508.94)
StoresProduct.create(store_id: 3, product_id: 8, price: 139.19)
StoresProduct.create(store_id: 3, product_id: 9, price: 831.41)
StoresProduct.create(store_id: 3, product_id: 10, price: 761.93)
StoresProduct.create(store_id: 3, product_id: 11, price: 896.20)
StoresProduct.create(store_id: 3, product_id: 12, price: 597.67)
StoresProduct.create(store_id: 3, product_id: 13, price: 577.33)
StoresProduct.create(store_id: 3, product_id: 14, price: 373.42)
StoresProduct.create(store_id: 3, product_id: 15, price: 740.03)
StoresProduct.create(store_id: 3, product_id: 16, price: 858.20)
StoresProduct.create(store_id: 3, product_id: 17, price: 418.01)
StoresProduct.create(store_id: 3, product_id: 18, price: 925.84)

StoresProduct.create(store_id: 4, product_id: 1, price: 725.02)
StoresProduct.create(store_id: 4, product_id: 2, price: 642.04)
StoresProduct.create(store_id: 4, product_id: 3, price: 755.63)
StoresProduct.create(store_id: 4, product_id: 4, price: 789.99)
StoresProduct.create(store_id: 4, product_id: 5, price: 315.36)
StoresProduct.create(store_id: 4, product_id: 6, price: 210.62)
StoresProduct.create(store_id: 4, product_id: 7, price: 994.42)
StoresProduct.create(store_id: 4, product_id: 8, price: 292.48)
StoresProduct.create(store_id: 4, product_id: 9, price: 108.54)
StoresProduct.create(store_id: 4, product_id: 10, price: 514.42)
StoresProduct.create(store_id: 4, product_id: 11, price: 179.70)
StoresProduct.create(store_id: 4, product_id: 12, price: 935.63)
StoresProduct.create(store_id: 4, product_id: 13, price: 557.23)
StoresProduct.create(store_id: 4, product_id: 14, price: 707.34)
StoresProduct.create(store_id: 4, product_id: 15, price: 102.35)
StoresProduct.create(store_id: 4, product_id: 16, price: 152.34)
StoresProduct.create(store_id: 4, product_id: 17, price: 862.26)
StoresProduct.create(store_id: 4, product_id: 18, price: 579.92)
